language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
script: pytest pallets/tests --cov pallets
after_success:
  - codecov
