sudo: required
language: python
python:
  - 3.7
services: docker
install:
  - docker-compose up -d --build
script:
  - docker-compose exec website pallets cov
  - docker-compose exec website pallets flake8
  - docker-compose exec website pallets test
after_success:
  - codecov
