version: "3.8"

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
          --access-logfile -
          --reload
          "pallets.app:create_app()"
    volumes:
      - ".:/pallets"
    ports:
      - "8000:8000"
