version: "3.8"

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
          --access-logfile -
          --reload
          "pallets.app:create_app()"
    volumes:
      - ".:/pallets"
    ports:
      - "8000:8000"
  redis:
    image: "redis:3.0-alpine"
    command: redis-server --requirepass devpassword
    volumes:
      - "redis:/var/lib/redis/data"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery worker -l info -A pallets.blueprints.contact.tasks
    env_file:
      - ".env"
    volumes:
      - ".:/pallets"

volumes:
  redis:
