version: "3.8"

services:
    website:
        build: .
        command: >
            gunicorn -b 0.0.0.0:8000
                --access-logfile -
                --reload
                "fragy.app:create_app()"
        volumes:
        - '.:/fragy'
        ports:
        - '8000:8000'
